format = " $all"

[directory]
format = "ğŸ¦• ï…¹ [ï¼ $path]($style)[$read_only]($read_only_style) "
style = "bold"
truncation_length = 8
truncate_to_repo = false

[git_branch]
style = "bold #dd0b78"

[conda]
ignore_base = false

[battery]
disabled = true

[character]
format = " $symbol "

[docker_context]
disabled = true

[package]
disabled = true
